# Site settings
title: Varun Patel's CV
description: varunpatel's CV
favicon: /GitPages/assets/img/avatar.JPG

# Build settings
markdown: kramdown

# Author settings
author:
  name: Varun Patel
  title: Java Developer
  address: University Park, Pennsylvania
  email: varun@verve3.io
  link: http://rainmaker490.github.io
  weibo:
  github: rainmaker490
  linkedin: rainmaker490
  twitter: rainmaker490
  gavatar: /GitPages/assets/img/avatar.JPG
  workHistory:
    - work1:
      company: The Pennsylvania State University
      location: University Park, PA
      title: Software Developer
      started: 2015
      duration: (Jan 2015 - May 2015)
      description:
        - description1: 
          caption: '• Led a group of 5 peers.'
        - description2: 
          caption: '• Worked on Application that allows Distance Education Students to submit programming assignments online and get instant feedback(stylecheck errors, output correctness, compilation errors) (Java, Bash, PHP).'
        - description3: 
          caption: '• Developed queue to run workloads requested by client to be processed on the server (server-side systems code)(Bash/PHP).'
        - description4: 
          caption: '• Developed and refactored Client-Side code to optimize (Java).'
        - description5: 
          caption: '• Refactored structure of server-side code for better design (Bash/PHP).'
    - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2014 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: The Pennsylvania State University
      degree: Bachelor of Science
      major: Computer Science
      started: 2015
      duration: (2010 - 2015)
      description: Minor - Mathematics
  languages:
    - language1:
      name: Gujarati
      proficiency: Native
    - language2:
      name: English
      proficiency: Native
    - language3:
      name: Hindi
      proficiency: Proficient
  programmingSkills:
    - skill1:
      name: Java
      percentage: 90%
    - skill2:
      name: Swift
      percentage: 80%
    - skill3:
      name: C++
      percentage: 75%
    - skill4:
      name: C
      percentage: 75%
    - skill5:
      name: Bash Scripting
      percentage: 80%
    - skill6:
      name: Parse
      percentage: 80%
    - skill7:
      name: Mapbox
      percentage: 80%
    - skill8:
      name: XCode
      percentage: 90%
    - skill9:
      name: Eclipse
      percentage: 90%
    
