# Site settings
title: Varun Patel's CV
description: varunpatel's CV
favicon: /GitPages/assets/img/avatar.JPG

# Build settings
markdown: kramdown

# Author settings
author:
  name: Varun Patel
  title: Software Developer (seeking full time opportunities in the LA / Bay Area)
  address: University Park, Pennsylvania
  email: varun@verve3.io
  link: http://rainmaker490.github.io
  weibo:
  github: rainmaker490
  linkedin: rainmaker490
  twitter: rainmaker490
  gavatar: /GitPages/assets/img/avatar.JPG
  workHistory:
    - work1:
      company: The Pennsylvania State University
      location: University Park, PA
      title: Software Developer
      started: 2015
      duration: (Jan 2015 - May 2015)
      description:
        - description1: 
          caption: '• Led a group of 5 peers.'
        - description2: 
          caption: '• Worked on Application that allows Distance Education Students to submit programming assignments online and get instant feedback(stylecheck errors, output correctness, compilation errors) (Java, Bash, PHP).'
        - description3: 
          caption: '• Developed queue to run workloads requested by client to be processed on the server (server-side systems code)(Bash/PHP).'
        - description4: 
          caption: '• Developed and refactored Client-Side code to optimize (Java).'
        - description5: 
          caption: '• Refactored structure of server-side code for better design (Bash/PHP).'
    - work2:
      company: IBM
      location: Las Vegas, NV
      title: Software Development Engineering Intern
      started: 2014
      duration: (July 2014 - Dec 2014)
      description: 
        - description1: 
          caption: '• Developed utility to automate the deployment of TRIRIGA onto application servers. (Java/ Bash Scripts).'
        - description2: 
          caption: '• Developed utility to automate publishing of the latest TRIRIGA build (upgrade server) (Java/ Bash Scripts/Python).'
        - description3: 
          caption: '• Developed utility to import / export Oracle databases (Bash Scripts).'
        - description4: 
          caption: '• Set up continuous delivery environments to be used by QA for quick-fix defect testing. (IBM SCO, CloudStack).'
        - description5: 
          caption: '• Built linux servers (RHEL 7).'
        - description6: 
          caption: '• Developed Bash Scripts to meet pre-install criteria (on RHEL 7) (modification of kernel-parameters) to install Oracle Database 12c.'
        - description7: 
          caption: '• Developed Automation Library utilizing Automation Framework 2.0 for QA testers with minimal development background (Java).'
        - description8: 
          caption: '• Worked / Resolved on Automation Framework 2.0 defects (Java).'
    - work3:
      company: IBM
      location: San Ramon, CA
      title: Software Development Engineering Intern
      started: 2014
      duration: (Jan 2014 - July 2014)      
      description: 
        - description1: 
          caption: '• Worked on Integrated Workplace Management Systems.'
        - description2: 
          caption: '• Developed Automation Framework (Automation Framework 2.0) used for QA regression testing (Java/Selenium API).'
        - description3: 
          caption: '• Developed regression tests utilizing Automation Framework (Java / Selenium API).'
        - description4: 
          caption: '• Developed test scripts for configuring and running tests on IWMS, deployed in development cycle (Java).'
        - description5: 
          caption: '• Worked on / Resolved issues reported via test script analyses [Automation Framework defects] (Java).'
        - description6: 
          caption: '• Worked with Java, Bash/Batch scripting languages.'
  projects:
    - project1:
      company: UCLA / LA Hacks
      location: Los Angeles, CA
      title: Hacker / Software Developer
      started: 2014
      duration: (April 2014)
      description:
        - description1:
          caption: '• Developed a turn-based game for iOS in 36 hours'
        - description2:
          caption: '• Utilized Sprite Kit to develop game (Objective C Framework)'
        - description3:
          caption: '• Developed back end & AI for Mystic Army'
        - description4:
          caption: '• Worked with a group of 3 (2 developers & 1 artist) [team member info available upon request]'
        - description5:
          caption: '• DEMO: http://lahacks.challengepost.com/submissions/22781-mystic-army)'
    - project2:
      company: The Pennsylvania State University / Code PSU
      location: University Park, PA
      title: Hacker / Software Developer
      started: 2013
      duration: (Feb 2013)
      description:
        - description1:
          caption: '• 2nd Place in the Intermediate Tier with a group of 3.'
        - description2:
          caption: '• ICPC-style programming competition hosted by the Penn State ACM and Penn State AWC. (http://acm.psu.edu/codepsu)'
        - description3:
          caption: '• Used C++ and Java to solve problems.'
  educationHistory:
    - education1:
      organization: The Pennsylvania State University
      degree: Bachelor of Science
      major: Computer Science
      started: 2015
      duration: (2010 - 2015)
      description: Minor - Mathematics
  languages:
    - language1:
      name: Gujarati
      proficiency: Native
    - language2:
      name: English
      proficiency: Native
    - language3:
      name: Hindi
      proficiency: Proficient
  programmingSkills:
    - skill1:
      name: Java
      percentage: 90%
    - skill2:
      name: Swift
      percentage: 80%
    - skill3:
      name: C++
      percentage: 75%
    - skill4:
      name: C
      percentage: 75%
    - skill5:
      name: Bash Scripting
      percentage: 80%
    - skill6:
      name: Parse
      percentage: 80%
    - skill7:
      name: Mapbox
      percentage: 80%
    - skill8:
      name: XCode
      percentage: 90%
    - skill9:
      name: Eclipse
      percentage: 90%
    
