# Site settings
title: Varun Patel's CV
description: varunpatel's CV
favicon: /GitPages/assets/img/avatar.JPG

# Build settings
markdown: kramdown

# Author settings
author:
  name: Varun Patel
  title: Software Engineer
  address: University Park, Pennsylvania
  email: varun@verve3.io
  link: http://rainmaker490.github.io
  weibo:
  github: rainmaker490
  linkedin: rainmaker490
  twitter: rainmaker490
  gavatar: /GitPages/assets/img/avatar.JPG
  workHistory:
    - work1:
      company: The Pennsylvania State University
      location: University Park, PA
      title: Software Developer
      started: 2015
      duration: (Jan 2015 - May 2015)
      description:
        - description1:
          link: '/assets/demo/CSE_PASS.pdf'
          linkDescription: '***Click Me to view Features Implemented & architecture/scope of project***' 
        - description2: 
          caption: '•  Led a group of 5 peers.'
        - description3: 
          caption: '•  Worked on Application that allows Distance Education Students to submit programming assignments online and get instant feedback(stylecheck errors, output correctness, compilation errors) (Java, Bash, PHP).'
        - description4: 
          caption: '•  Developed queue to run workloads requested by client to be processed on the server (server-side systems code)(Bash/PHP).'
        - description5: 
          caption: '•  Developed and refactored Client-Side code to optimize (Java).'
        - description6: 
          caption: '•  Refactored structure of server-side code for better design (Bash/PHP).'
    - work2:
      company: IBM
      location: Las Vegas, NV
      title: Software Development Engineering Intern
      started: 2014
      duration: (July 2014 - Dec 2014)
      description: 
        - description1: 
          caption: '•  Developed utility to automate the deployment of TRIRIGA onto application servers. (Java/ Bash Scripts).'
        - description2: 
          caption: '•  Developed utility to automate publishing of the latest TRIRIGA build (upgrade server) (Java/ Bash Scripts/Python).'
        - description3: 
          caption: '•  Developed utility to import / export Oracle databases (Bash Scripts).'
        - description4: 
          caption: '•  Set up continuous delivery environments to be used by QA for quick-fix defect testing. (IBM SCO, CloudStack).'
        - description5: 
          caption: '•  Built linux servers (RHEL 7).'
        - description6: 
          caption: '•  Developed Bash Scripts to meet pre-install criteria (on RHEL 7) (modification of kernel-parameters) to install Oracle Database 12c.'
        - description7: 
          caption: '•  Developed Automation Library utilizing Automation Framework 2.0 for QA testers with minimal development background (Java).'
        - description8: 
          caption: '•  Worked / Resolved on Automation Framework 2.0 defects (Java).'
    - work3:
      company: IBM
      location: San Ramon, CA
      title: Software Development Engineering Intern
      started: 2014
      duration: (Jan 2014 - July 2014)      
      description: 
        - description1: 
          caption: '•  Worked on Integrated Workplace Management Systems.'
        - description2: 
          caption: '•  Developed Automation Framework (Automation Framework 2.0) used for QA regression testing (Java/Selenium API).'
        - description3: 
          caption: '•  Developed regression tests utilizing Automation Framework (Java / Selenium API).'
        - description4: 
          caption: '•  Developed test scripts for configuring and running tests on IWMS, deployed in development cycle (Java).'
        - description5: 
          caption: '•  Worked on / Resolved issues reported via test script analyses [Automation Framework defects] (Java).'
        - description6: 
          caption: '•  Worked with Java, Bash/Batch scripting languages.'
  projects:
    - project1:
      company: HackPSU - 2nd Place Overall at Hackathon
      location: University Park, PA
      title: Hacker / Software Developer
      started: 2015
      duration: (November 2015)
      description:
        - description1: 
          caption:
            - caption: '•  Name of App: Pulse'
            - caption: '•  Pulse is an all in one mobile solution to competitive classroom participation. Pulse allows a teacher to create a virtual “class”, add his/her students, and create sets of questions and answers for his/her students to answer in real time. ' 
        - description3:
          caption:
            - caption: '•  Developed a tvOS App (for Apple TV), and an iPad/iPhone/iPod App'
        - description4:
          caption:
            - caption: '•  Utilized Swift and Parse'
        - description5:
          caption:
            - caption: '•  Developed parts of back end & iPad/iPhone/iPod app'
        - description6:
          link:
            - description: '•  Worked with a group of 3 (3 developers):'
            - link: 'https://github.com/Mmarzex'
            - link: 'https://github.com/mdr5325'
        - description7:
          caption:
            - caption: '•  DEMO :'
          link:
            - link: 'http://rainmaker490.github.io/pulse/'
    - project2:
      company: UCLA / LA Hacks
      location: Los Angeles, CA
      title: Hacker / Software Developer
      started: 2014
      duration: (April 2014)
      description:
        - description1:
          caption:
            - caption: '•  Developed a turn-based game for iOS in 36 hours'
        - description2:
          caption:
            - caption: '•  Utilized Sprite Kit to develop game (Objective C Framework)'
        - description3:
          caption:
            - caption: '•  Developed back end & AI for Mystic Army'
        - description4:
          caption:
            - caption: '•  Worked with a group of 3 (2 developers & 1 artist) [team member info available upon request]'
        - description5:
          link:
            - description: '•  DEMO : '
            - link: 'http://lahacks.challengepost.com/submissions/22781-mystic-army)'
            
    - project3:
      company: The Pennsylvania State University / Code PSU - 2nd Place in the Intermediate Tier
      location: University Park, PA
      title: Hacker / Software Developer
      started: 2013
      duration: (Feb 2013)
      description:
        - description1:
          link:
            - description: '•  Coordinated by ACM at PSU'
            - link: 'http://acm.psu.edu/codepsu'
        - description2:
          caption:
            - caption: '•  Worked with a group of 3 peers'
        - description3:
          caption:
            - caption: '•  ICPC-style programming competition hosted by the Penn State ACM and Penn State AWC.'
        - description4:
          caption:
            - caption: '•  Used C++ and Java to solve problems.'
  courseWorkProjects:
    - course1:
      company: Application-Space Device Driver
      location: University Park, PA
      started: 2013
      duration: (December 2013)
      description:
        - description1:
          caption: '•  Developed an operating system (linux) interface using C that read and wrote buffered data for a virtual storage device.'
        - description2:
          caption: '•  Implemented the device driver to use network connection to send and receive commands.'
    - course2:
      company: Numerical Analysis And Computation
      location: University Park, PA
      title: Random Walks and Financial Option Pricing
      started: 2013
      duration: (September 2013)
      description:
        - description1:
          caption: '•  Analyzed the correlation of randomly generated walks with stock prices.'
        - description2:
          caption: '•  Developed a model using Matlab to price a European call option using a random walk. (Monte-Carlo method)'
    - course2:
      company: Numerical Analysis And Computation
      location: University Park, PA
      title: Interpolation & Images
      started: 2013
      duration: (September 2013)
      description:
        - description1:
          caption: '•  Developed scripts in Matlab to mathematically analyze interpolation of images using Bilinear, Nearest-Neighbor, Linear, Cubic, and Spline Interpolations.'
  educationHistory:
    - education1:
      organization: The Pennsylvania State University
      degree: Bachelor of Science
      major: Computer Science
      started: 2015
      duration: (2010 - 2015)
      description: Minor - Mathematics
  organizations:
    - organization1:
      organization: ACM
      started: 2013
      duration: (2013 - 2015)
      description:
        - description1:
          caption: '•  Recognized by A.C.M. at The Pennsylvania State University as the most Active member for the Spring 2013 Semester.'
  languages:
    - language1:
      name: Gujarati
      proficiency: Native
    - language2:
      name: English
      proficiency: Native
    - language3:
      name: Hindi
      proficiency: Proficient
  programmingLanguages:
    - skill1:
      name: Java
      percentage: 90%
    - skill2:
      name: Swift
      percentage: 80%
    - skill3:
      name: C++
      percentage: 75%
    - skill4:
      name: C
      percentage: 75%
    - skill5:
      name: Bash Scripting
      percentage: 80%
  programmingSkills:
    - skill1:
      name: Parse
      percentage: 80%
    - skill2:
      name: Mapbox
      percentage: 80%
    - skill3:
      name: XCode
      percentage: 90%
    - skill4:
      name: Eclipse
      percentage: 90%
    - skill5:
      name: Git
      percentage: 90%
    - skill6:
      name: Selenium
      percentage: 60%
      
    
